In [32]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [33]:
df=pd.read_csv(r"..\data\labels.csv",header=None)

In [34]:
df

                                                  0
0     images/cell0001.png  1.0                 mono
1     images/cell0002.png  1.0                 mono
2     images/cell0003.png  1.0                 mono
3     images/cell0004.png  0.0                 mono
4     images/cell0005.png  1.0                 mono
...                                             ...
2619  images/cell2620.png  0.0                 poly
2620  images/cell2621.png  0.0                 poly
2621  images/cell2622.png  0.0                 poly
2622  images/cell2623.png  0.0                 poly
2623  images/cell2624.png  0.0                 poly

[2624 rows x 1 columns]

In [35]:
df.columns=['one']

In [36]:
df['path']=df['one'].str.split(' ').str[0]
df['label']=df['one'].str.split(' ').str[2].astype('Float64').round(2)
df['type']=df['one'].str.split(' ').str[-1]
df.drop('one',axis=1,inplace=True)
df.to_csv('../data/fixed_labels.csv',header=True)

In [37]:
df['label'].value_counts()

label
0.0     1508
1.0      715
0.33     295
0.67     106
Name: count, dtype: Int64

In [38]:
df

                     path  label  type
0     images/cell0001.png    1.0  mono
1     images/cell0002.png    1.0  mono
2     images/cell0003.png    1.0  mono
3     images/cell0004.png    0.0  mono
4     images/cell0005.png    1.0  mono
...                   ...    ...   ...
2619  images/cell2620.png    0.0  poly
2620  images/cell2621.png    0.0  poly
2621  images/cell2622.png    0.0  poly
2622  images/cell2623.png    0.0  poly
2623  images/cell2624.png    0.0  poly

[2624 rows x 3 columns]

In [39]:
le=LabelEncoder()
df['type']=le.fit_transform(df['type'])
df

                     path  label  type
0     images/cell0001.png    1.0     0
1     images/cell0002.png    1.0     0
2     images/cell0003.png    1.0     0
3     images/cell0004.png    0.0     0
4     images/cell0005.png    1.0     0
...                   ...    ...   ...
2619  images/cell2620.png    0.0     1
2620  images/cell2621.png    0.0     1
2621  images/cell2622.png    0.0     1
2622  images/cell2623.png    0.0     1
2623  images/cell2624.png    0.0     1

[2624 rows x 3 columns]

In [40]:
X=df.drop('label',axis=1)
y=df['label']

In [41]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42,stratify=y_temp)

In [42]:
train_df=pd.concat([X_train,y_train],axis=1)
test_df=pd.concat([X_test,y_test],axis=1)
val_df=pd.concat([X_val,y_val],axis=1)

In [43]:
test_df.reset_index(inplace=True)
train_df.reset_index(inplace=True)
val_df.reset_index(inplace=True)

In [44]:
test_df.drop('index',axis=1,inplace=True)
val_df.drop('index',axis=1,inplace=True)
train_df.drop('index',axis=1,inplace=True)

In [45]:
train_df.to_csv('../data/train_data.csv')
test_df.to_csv('../data/test_data.csv')
val_df.to_csv('../data/val_data.csv')